import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/header/header";
import styles from "./index.module.css";
import layout from "../styles/layout.module.css";
import registration from '../styles/registrationForm.module.css'
import typography from "../styles/typography.module.css";
import cx from "classix";
import React, { useState } from "react";
import axios from 'axios';
//import { PrismaClient } from "@prisma/client";


const Home: NextPage = () => {
  const [ firstName, setFirstName ] = useState('');
  const [ surName, setSurName ] = useState('');
  const [ email, setEmail ] = useState('');
  const [ message, setMessage ] = useState(''); 
  const [ title, setTitle] = useState('');
  const [ errorMessage, setErrorMessage] = useState(['Doctor', 'Prof.', 'Prof.Dr.']);
  
 
  //const prisma = new PrismaClient();


  const handleFirstName = e => setFirstName(e.target.value);
  const handleSurName = e => setSurName(e.target.value);
  const handleEmail = e => setEmail(e.target.value);
  const handleMessage = e => setMessage(e.target.value);

  const handleSubmit = async e => {
    e.preventDefault();
    const requestBody = { firstName, surName, email, message };

    /* const user = prisma.user.create({
      data: {
        firstName, surName, email, message
      }
    }) */

    //console.log(requestBody)
    axios.post('/registrations', requestBody)
      .then(response => {
        console.log(response);
      })
      .catch((err) => console.log(err)) 
  }
  
  return (
    <>
      <div>
        <Head>
          <title>Atelier Disko Coding Challenge</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Header />

      <div>
        <form onSubmit={handleSubmit}>
          <div className={registration.container}>
           {/*   <select onChange={handleTitleChange}>
              
             </select> */} 

             <label>Firstname</label>   
              <input
                value={firstName}
                onChange={handleFirstName}
                type='text'
                placeholder="Hans"
                required
                 />
                </div> 

              <label>Surname</label>
              <input
                value={surName}
                onChange={handleSurName}
                type='text'
                placeholder="Fuchs"
                required
                 />

              <label>Email</label>
              <input
                value={email}
                onChange={handleEmail}
                type='email'
                placeholder="fuchs@hans.com"
                required
                 />

              <label>Message</label>
              <textarea
                value={message}
                onChange={handleMessage}
                type='text'
                placeholder="Your message goes here"
              ></textarea>

              <button>Enter</button>
          
        </form>
      </div>    

{/*           <div className={cx(layout.container, layout.grid)}>
            <div>This</div>
            <div>is</div>
            <div>a</div>
            <div>sample</div>
            <div>grid</div>
            <div>with</div>
            <div>twelve</div>
            <div>columns</div>
            <div>and</div>
            <div>20px</div>
            <div>gutter</div>
          </div> */}
        </main>
      </div>
    </>
  );
};

export default Home;
